version: '3'

volumes:
  gitlab-data:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/opt/gitlab
  gitlab-config:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/etc/gitlab
  gitlab-logs:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/log/gitlab

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_URL}'
        registry_external_url 'https://${GITLAB_REGISTRY}'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['gitlab_email_from'] = "${FROM_MAIL}"
        gitlab_rails['gitlab_email_reply_to'] = "${REPLY_TO_MAIL}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTH}"
        gitlab_rails['smtp_enable_starttls_auto'] = "${STARTTLS}"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PW}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PROTO: HTTP
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - gitlab-data:/etc/gitlab
      - gitlab-config:/var/log/gitlab
      - gitlab-logs:/var/opt/gitlab
    networks:
      - nginxproxy
    ports:
      - ${PROXYPORTSSH}:22

networks:
  nginxproxy:
    external:
      name: ${NGINXPROXYNETWORK}
