version: '3'

volumes:
  openvpn-data:
     driver_opts:
       type: none
       device: ${CONTAINERVOLUME}/etc/openvpn
       o: bind

services:
  openvpn:
    image: kylemanna/openvpn
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - openvpn-data:/etc/openvpn
    ports:
      - ${PROXYPORT}:1194/udp
    cap_add:
      - NET_ADMIN
    networks:
      - nginxproxy
      - default

networks:
  nginxproxy:
    external:
      name: ${NGINXPROXYNETWORK}
